- name: Install and Build
        run: |
          npm install
          # Usamos build normal para evitar el error del archivo environment.prod.ts
          npx ng build --base-href /Say_Tattoo-_ProyectoFullStack/
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/proyecto-final-angular
          branch: gh-pages
