name: Build and Deploy
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install and Build
        # El comando 'cd' es la clave: entra en la carpeta donde está el código real
        run: |
          cd Say_Tattoo-_ProyectoFullStack
          npm install --legacy-peer-deps
          npx ng build --base-href /Say_Tattoo-_ProyectoFullStack/ --output-path dist

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # Aquí también le decimos dónde acabó el resultado
          folder: Say_Tattoo-_ProyectoFullStack/dist
          branch: gh-pages
